import type { Metadata } from "next";
import { IBM_Plex_Sans, IBM_Plex_Mono, DM_Sans } from "next/font/google";
import "@/styles/app.css";
import { AuthKitProvider } from "@workos-inc/authkit-nextjs/components";
import { Analytics } from "@vercel/analytics/next";

const plexSans = IBM_Plex_Sans({
  variable: "--font-plex-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const plexMono = IBM_Plex_Mono({
  variable: "--font-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plexSans.variable} ${plexMono.variable} ${dmSans.variable} w-screen min-h-screen`}
      >
        <AuthKitProvider>{children}</AuthKitProvider>
        <Analytics />
      </body>
    </html>
  );
}
